### PR TITLE
Organize the repo so (short) docs are in the root readme.

### PR DESCRIPTION
**Pull request by StevenBlack**
If merged, this PR reorganizes the repo so docs are in the root readme, not in a separate markdown file.

Also the .pdf version of docs is deleted since there is no pipeline to keep the .pdf updated.  Also because, who uses .pdf versions of docs, ever?

### CODE REVIEW

**Comment by RickStrahl** [comment]
Ha - that was my first thought here too :-) Good call, Steve.

**Comment by StevenBlack** [comment]
@rickborup ping!

**Comment by RickBorup** [comment]
Hey, Steve. Thanks for your interest in the project.

Readme is a synopsis. Full documentation is separate because it changes as the project evolves, while readme stays the same.

Docs are included in PDF format as a convenience for anyone who might prefer it for offline reference. The PDF is a straight-up export of the markdown file using Markdown Monster, so it stays in sync.

**Comment by StevenBlack** [comment]
I understand.  Not sure I buy the reasoning you cite, but whatever.

Just wondering if you can locate a repo among the 10M here on Github that do it this way?    In other words, what do you know that the overwhelmingly vast majority of repo maintainers don't?  From this vantage, what I observe is readme do a heck of a lot more than synopsis, as you state, considering the downsides of click-burying the meat of the matter.

I presume you're aware of `git clone`, so the *offline* use case is fully covered by long standing, standard practice.

The PDF pipeline should be documented, and the repo should include MarkDown Monster config files, if any exist (I don't know).

I sense you dumped this here (which is nominally good) without much thought about how Github is used, in normal practice (not so good).

**Comment by StevenBlack** [comment]
closing.

**Pull request closed without merging**
